apiVersion: v1
kind: Pod
metadata:
  name: elder-grater
  namespace: default
  labels:
    app: elder-grater  
spec:
  serviceAccountName: default
  containers:
  - name: elder-grater 
    image: replace-me.dkr.ecr.us-west-2.amazonaws.com/elder-grater:latest
    imagePullPolicy: Always
